name: "Destroy and Mount Terraform"

on:
  push:
    paths:
      - "conf/**"
      - "scripts/**"

jobs:
  destroy-mount:
    name: "Destroy and mount"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
